library(ape)
library(phangorn)
library(phytools)
speciestree <- read.tree('/Users/danielle/Desktop/phylogeny_maptoNlecref/2021_Nov/windows/1mb-astral.tre')
windowtrees <- read.tree('/Users/danielle/Desktop/phylogeny_maptoNlecref/2021_Nov/windows/500kb-filteredmissing.trees')
speciestree
windowtrees
sink("/Users/danielle/Desktop/phylogeny_maptoNlecref/2021_Nov/windows/painting/500kb-treedistance.matrix",append=TRUE)
cat(treedist(speciestree,windowtrees[[1]]),'
')
cat(treedist(speciestree,windowtrees[[2]]),'
')
cat(treedist(speciestree,windowtrees[[3]]),'
')
cat(treedist(speciestree,windowtrees[[4]]),'
')
cat(treedist(speciestree,windowtrees[[5]]),'
')
cat(treedist(speciestree,windowtrees[[6]]),'
')
cat(treedist(speciestree,windowtrees[[7]]),'
')
cat(treedist(speciestree,windowtrees[[8]]),'
')
cat(treedist(speciestree,windowtrees[[9]]),'
')
cat(treedist(speciestree,windowtrees[[10]]),'
')
cat(treedist(speciestree,windowtrees[[11]]),'
')
cat(treedist(speciestree,windowtrees[[12]]),'
')
cat(treedist(speciestree,windowtrees[[13]]),'
')
cat(treedist(speciestree,windowtrees[[14]]),'
')
cat(treedist(speciestree,windowtrees[[15]]),'
')
cat(treedist(speciestree,windowtrees[[16]]),'
')
cat(treedist(speciestree,windowtrees[[17]]),'
')
cat(treedist(speciestree,windowtrees[[18]]),'
')
cat(treedist(speciestree,windowtrees[[19]]),'
')
cat(treedist(speciestree,windowtrees[[20]]),'
')
cat(treedist(speciestree,windowtrees[[21]]),'
')
cat(treedist(speciestree,windowtrees[[22]]),'
')
cat(treedist(speciestree,windowtrees[[23]]),'
')
cat(treedist(speciestree,windowtrees[[24]]),'
')
cat(treedist(speciestree,windowtrees[[25]]),'
')
cat(treedist(speciestree,windowtrees[[26]]),'
')
cat(treedist(speciestree,windowtrees[[27]]),'
')
cat(treedist(speciestree,windowtrees[[28]]),'
')
cat(treedist(speciestree,windowtrees[[29]]),'
')
cat(treedist(speciestree,windowtrees[[30]]),'
')
cat(treedist(speciestree,windowtrees[[31]]),'
')
cat(treedist(speciestree,windowtrees[[32]]),'
')
cat(treedist(speciestree,windowtrees[[33]]),'
')
cat(treedist(speciestree,windowtrees[[34]]),'
')
cat(treedist(speciestree,windowtrees[[35]]),'
')
cat(treedist(speciestree,windowtrees[[36]]),'
')
cat(treedist(speciestree,windowtrees[[37]]),'
')
cat(treedist(speciestree,windowtrees[[38]]),'
')
cat(treedist(speciestree,windowtrees[[39]]),'
')
cat(treedist(speciestree,windowtrees[[40]]),'
')
cat(treedist(speciestree,windowtrees[[41]]),'
')
cat(treedist(speciestree,windowtrees[[42]]),'
')
cat(treedist(speciestree,windowtrees[[43]]),'
')
cat(treedist(speciestree,windowtrees[[44]]),'
')
cat(treedist(speciestree,windowtrees[[45]]),'
')
cat(treedist(speciestree,windowtrees[[46]]),'
')
cat(treedist(speciestree,windowtrees[[47]]),'
')
cat(treedist(speciestree,windowtrees[[48]]),'
')
cat(treedist(speciestree,windowtrees[[49]]),'
')
cat(treedist(speciestree,windowtrees[[50]]),'
')
cat(treedist(speciestree,windowtrees[[51]]),'
')
cat(treedist(speciestree,windowtrees[[52]]),'
')
cat(treedist(speciestree,windowtrees[[53]]),'
')
cat(treedist(speciestree,windowtrees[[54]]),'
')
cat(treedist(speciestree,windowtrees[[55]]),'
')
cat(treedist(speciestree,windowtrees[[56]]),'
')
cat(treedist(speciestree,windowtrees[[57]]),'
')
cat(treedist(speciestree,windowtrees[[58]]),'
')
cat(treedist(speciestree,windowtrees[[59]]),'
')
cat(treedist(speciestree,windowtrees[[60]]),'
')
cat(treedist(speciestree,windowtrees[[61]]),'
')
cat(treedist(speciestree,windowtrees[[62]]),'
')
cat(treedist(speciestree,windowtrees[[63]]),'
')
cat(treedist(speciestree,windowtrees[[64]]),'
')
cat(treedist(speciestree,windowtrees[[65]]),'
')
cat(treedist(speciestree,windowtrees[[66]]),'
')
cat(treedist(speciestree,windowtrees[[67]]),'
')
cat(treedist(speciestree,windowtrees[[68]]),'
')
cat(treedist(speciestree,windowtrees[[69]]),'
')
cat(treedist(speciestree,windowtrees[[70]]),'
')
cat(treedist(speciestree,windowtrees[[71]]),'
')
cat(treedist(speciestree,windowtrees[[72]]),'
')
cat(treedist(speciestree,windowtrees[[73]]),'
')
cat(treedist(speciestree,windowtrees[[74]]),'
')
cat(treedist(speciestree,windowtrees[[75]]),'
')
cat(treedist(speciestree,windowtrees[[76]]),'
')
cat(treedist(speciestree,windowtrees[[77]]),'
')
cat(treedist(speciestree,windowtrees[[78]]),'
')
cat(treedist(speciestree,windowtrees[[79]]),'
')
cat(treedist(speciestree,windowtrees[[80]]),'
')
cat(treedist(speciestree,windowtrees[[81]]),'
')
cat(treedist(speciestree,windowtrees[[82]]),'
')
cat(treedist(speciestree,windowtrees[[83]]),'
')
cat(treedist(speciestree,windowtrees[[84]]),'
')
cat(treedist(speciestree,windowtrees[[85]]),'
')
cat(treedist(speciestree,windowtrees[[86]]),'
')
cat(treedist(speciestree,windowtrees[[87]]),'
')
cat(treedist(speciestree,windowtrees[[88]]),'
')
cat(treedist(speciestree,windowtrees[[89]]),'
')
cat(treedist(speciestree,windowtrees[[90]]),'
')
cat(treedist(speciestree,windowtrees[[91]]),'
')
cat(treedist(speciestree,windowtrees[[92]]),'
')
cat(treedist(speciestree,windowtrees[[93]]),'
')
cat(treedist(speciestree,windowtrees[[94]]),'
')
cat(treedist(speciestree,windowtrees[[95]]),'
')
cat(treedist(speciestree,windowtrees[[96]]),'
')
cat(treedist(speciestree,windowtrees[[97]]),'
')
cat(treedist(speciestree,windowtrees[[98]]),'
')
cat(treedist(speciestree,windowtrees[[99]]),'
')
cat(treedist(speciestree,windowtrees[[100]]),'
')
cat(treedist(speciestree,windowtrees[[101]]),'
')
cat(treedist(speciestree,windowtrees[[102]]),'
')
cat(treedist(speciestree,windowtrees[[103]]),'
')
cat(treedist(speciestree,windowtrees[[104]]),'
')
cat(treedist(speciestree,windowtrees[[105]]),'
')
cat(treedist(speciestree,windowtrees[[106]]),'
')
cat(treedist(speciestree,windowtrees[[107]]),'
')
cat(treedist(speciestree,windowtrees[[108]]),'
')
cat(treedist(speciestree,windowtrees[[109]]),'
')
cat(treedist(speciestree,windowtrees[[110]]),'
')
cat(treedist(speciestree,windowtrees[[111]]),'
')
cat(treedist(speciestree,windowtrees[[112]]),'
')
cat(treedist(speciestree,windowtrees[[113]]),'
')
cat(treedist(speciestree,windowtrees[[114]]),'
')
cat(treedist(speciestree,windowtrees[[115]]),'
')
cat(treedist(speciestree,windowtrees[[116]]),'
')
cat(treedist(speciestree,windowtrees[[117]]),'
')
cat(treedist(speciestree,windowtrees[[118]]),'
')
cat(treedist(speciestree,windowtrees[[119]]),'
')
cat(treedist(speciestree,windowtrees[[120]]),'
')
cat(treedist(speciestree,windowtrees[[121]]),'
')
cat(treedist(speciestree,windowtrees[[122]]),'
')
cat(treedist(speciestree,windowtrees[[123]]),'
')
cat(treedist(speciestree,windowtrees[[124]]),'
')
cat(treedist(speciestree,windowtrees[[125]]),'
')
cat(treedist(speciestree,windowtrees[[126]]),'
')
cat(treedist(speciestree,windowtrees[[127]]),'
')
cat(treedist(speciestree,windowtrees[[128]]),'
')
cat(treedist(speciestree,windowtrees[[129]]),'
')
cat(treedist(speciestree,windowtrees[[130]]),'
')
cat(treedist(speciestree,windowtrees[[131]]),'
')
cat(treedist(speciestree,windowtrees[[132]]),'
')
cat(treedist(speciestree,windowtrees[[133]]),'
')
cat(treedist(speciestree,windowtrees[[134]]),'
')
cat(treedist(speciestree,windowtrees[[135]]),'
')
cat(treedist(speciestree,windowtrees[[136]]),'
')
cat(treedist(speciestree,windowtrees[[137]]),'
')
cat(treedist(speciestree,windowtrees[[138]]),'
')
cat(treedist(speciestree,windowtrees[[139]]),'
')
cat(treedist(speciestree,windowtrees[[140]]),'
')
cat(treedist(speciestree,windowtrees[[141]]),'
')
cat(treedist(speciestree,windowtrees[[142]]),'
')
cat(treedist(speciestree,windowtrees[[143]]),'
')
cat(treedist(speciestree,windowtrees[[144]]),'
')
cat(treedist(speciestree,windowtrees[[145]]),'
')
cat(treedist(speciestree,windowtrees[[146]]),'
')
cat(treedist(speciestree,windowtrees[[147]]),'
')
cat(treedist(speciestree,windowtrees[[148]]),'
')
cat(treedist(speciestree,windowtrees[[149]]),'
')
cat(treedist(speciestree,windowtrees[[150]]),'
')
cat(treedist(speciestree,windowtrees[[151]]),'
')
cat(treedist(speciestree,windowtrees[[152]]),'
')
cat(treedist(speciestree,windowtrees[[153]]),'
')
cat(treedist(speciestree,windowtrees[[154]]),'
')
cat(treedist(speciestree,windowtrees[[155]]),'
')
cat(treedist(speciestree,windowtrees[[156]]),'
')
cat(treedist(speciestree,windowtrees[[157]]),'
')
cat(treedist(speciestree,windowtrees[[158]]),'
')
cat(treedist(speciestree,windowtrees[[159]]),'
')
cat(treedist(speciestree,windowtrees[[160]]),'
')
cat(treedist(speciestree,windowtrees[[161]]),'
')
cat(treedist(speciestree,windowtrees[[162]]),'
')
cat(treedist(speciestree,windowtrees[[163]]),'
')
cat(treedist(speciestree,windowtrees[[164]]),'
')
cat(treedist(speciestree,windowtrees[[165]]),'
')
cat(treedist(speciestree,windowtrees[[166]]),'
')
cat(treedist(speciestree,windowtrees[[167]]),'
')
cat(treedist(speciestree,windowtrees[[168]]),'
')
cat(treedist(speciestree,windowtrees[[169]]),'
')
cat(treedist(speciestree,windowtrees[[170]]),'
')
cat(treedist(speciestree,windowtrees[[171]]),'
')
cat(treedist(speciestree,windowtrees[[172]]),'
')
cat(treedist(speciestree,windowtrees[[173]]),'
')
cat(treedist(speciestree,windowtrees[[174]]),'
')
cat(treedist(speciestree,windowtrees[[175]]),'
')
cat(treedist(speciestree,windowtrees[[176]]),'
')
cat(treedist(speciestree,windowtrees[[177]]),'
')
cat(treedist(speciestree,windowtrees[[178]]),'
')
cat(treedist(speciestree,windowtrees[[179]]),'
')
cat(treedist(speciestree,windowtrees[[180]]),'
')
cat(treedist(speciestree,windowtrees[[181]]),'
')
cat(treedist(speciestree,windowtrees[[182]]),'
')
cat(treedist(speciestree,windowtrees[[183]]),'
')
cat(treedist(speciestree,windowtrees[[184]]),'
')
cat(treedist(speciestree,windowtrees[[185]]),'
')
cat(treedist(speciestree,windowtrees[[186]]),'
')
cat(treedist(speciestree,windowtrees[[187]]),'
')
cat(treedist(speciestree,windowtrees[[188]]),'
')
cat(treedist(speciestree,windowtrees[[189]]),'
')
cat(treedist(speciestree,windowtrees[[190]]),'
')
cat(treedist(speciestree,windowtrees[[191]]),'
')
cat(treedist(speciestree,windowtrees[[192]]),'
')
cat(treedist(speciestree,windowtrees[[193]]),'
')
cat(treedist(speciestree,windowtrees[[194]]),'
')
cat(treedist(speciestree,windowtrees[[195]]),'
')
cat(treedist(speciestree,windowtrees[[196]]),'
')
cat(treedist(speciestree,windowtrees[[197]]),'
')
cat(treedist(speciestree,windowtrees[[198]]),'
')
cat(treedist(speciestree,windowtrees[[199]]),'
')
cat(treedist(speciestree,windowtrees[[200]]),'
')
cat(treedist(speciestree,windowtrees[[201]]),'
')
cat(treedist(speciestree,windowtrees[[202]]),'
')
cat(treedist(speciestree,windowtrees[[203]]),'
')
cat(treedist(speciestree,windowtrees[[204]]),'
')
cat(treedist(speciestree,windowtrees[[205]]),'
')
cat(treedist(speciestree,windowtrees[[206]]),'
')
cat(treedist(speciestree,windowtrees[[207]]),'
')
cat(treedist(speciestree,windowtrees[[208]]),'
')
cat(treedist(speciestree,windowtrees[[209]]),'
')
cat(treedist(speciestree,windowtrees[[210]]),'
')
cat(treedist(speciestree,windowtrees[[211]]),'
')
cat(treedist(speciestree,windowtrees[[212]]),'
')
cat(treedist(speciestree,windowtrees[[213]]),'
')
cat(treedist(speciestree,windowtrees[[214]]),'
')
cat(treedist(speciestree,windowtrees[[215]]),'
')
cat(treedist(speciestree,windowtrees[[216]]),'
')
cat(treedist(speciestree,windowtrees[[217]]),'
')
cat(treedist(speciestree,windowtrees[[218]]),'
')
cat(treedist(speciestree,windowtrees[[219]]),'
')
cat(treedist(speciestree,windowtrees[[220]]),'
')
cat(treedist(speciestree,windowtrees[[221]]),'
')
cat(treedist(speciestree,windowtrees[[222]]),'
')
cat(treedist(speciestree,windowtrees[[223]]),'
')
cat(treedist(speciestree,windowtrees[[224]]),'
')
cat(treedist(speciestree,windowtrees[[225]]),'
')
cat(treedist(speciestree,windowtrees[[226]]),'
')
cat(treedist(speciestree,windowtrees[[227]]),'
')
cat(treedist(speciestree,windowtrees[[228]]),'
')
cat(treedist(speciestree,windowtrees[[229]]),'
')
cat(treedist(speciestree,windowtrees[[230]]),'
')
cat(treedist(speciestree,windowtrees[[231]]),'
')
cat(treedist(speciestree,windowtrees[[232]]),'
')
cat(treedist(speciestree,windowtrees[[233]]),'
')
cat(treedist(speciestree,windowtrees[[234]]),'
')
cat(treedist(speciestree,windowtrees[[235]]),'
')
cat(treedist(speciestree,windowtrees[[236]]),'
')
cat(treedist(speciestree,windowtrees[[237]]),'
')
cat(treedist(speciestree,windowtrees[[238]]),'
')
cat(treedist(speciestree,windowtrees[[239]]),'
')
cat(treedist(speciestree,windowtrees[[240]]),'
')
cat(treedist(speciestree,windowtrees[[241]]),'
')
cat(treedist(speciestree,windowtrees[[242]]),'
')
cat(treedist(speciestree,windowtrees[[243]]),'
')
cat(treedist(speciestree,windowtrees[[244]]),'
')
cat(treedist(speciestree,windowtrees[[245]]),'
')
cat(treedist(speciestree,windowtrees[[246]]),'
')
cat(treedist(speciestree,windowtrees[[247]]),'
')
cat(treedist(speciestree,windowtrees[[248]]),'
')
cat(treedist(speciestree,windowtrees[[249]]),'
')
cat(treedist(speciestree,windowtrees[[250]]),'
')
cat(treedist(speciestree,windowtrees[[251]]),'
')
cat(treedist(speciestree,windowtrees[[252]]),'
')
cat(treedist(speciestree,windowtrees[[253]]),'
')
cat(treedist(speciestree,windowtrees[[254]]),'
')
cat(treedist(speciestree,windowtrees[[255]]),'
')
cat(treedist(speciestree,windowtrees[[256]]),'
')
cat(treedist(speciestree,windowtrees[[257]]),'
')
cat(treedist(speciestree,windowtrees[[258]]),'
')
cat(treedist(speciestree,windowtrees[[259]]),'
')
cat(treedist(speciestree,windowtrees[[260]]),'
')
cat(treedist(speciestree,windowtrees[[261]]),'
')
cat(treedist(speciestree,windowtrees[[262]]),'
')
cat(treedist(speciestree,windowtrees[[263]]),'
')
cat(treedist(speciestree,windowtrees[[264]]),'
')
cat(treedist(speciestree,windowtrees[[265]]),'
')
cat(treedist(speciestree,windowtrees[[266]]),'
')
cat(treedist(speciestree,windowtrees[[267]]),'
')
cat(treedist(speciestree,windowtrees[[268]]),'
')
cat(treedist(speciestree,windowtrees[[269]]),'
')
cat(treedist(speciestree,windowtrees[[270]]),'
')
cat(treedist(speciestree,windowtrees[[271]]),'
')
cat(treedist(speciestree,windowtrees[[272]]),'
')
cat(treedist(speciestree,windowtrees[[273]]),'
')
cat(treedist(speciestree,windowtrees[[274]]),'
')
cat(treedist(speciestree,windowtrees[[275]]),'
')
cat(treedist(speciestree,windowtrees[[276]]),'
')
cat(treedist(speciestree,windowtrees[[277]]),'
')
cat(treedist(speciestree,windowtrees[[278]]),'
')
cat(treedist(speciestree,windowtrees[[279]]),'
')
cat(treedist(speciestree,windowtrees[[280]]),'
')
cat(treedist(speciestree,windowtrees[[281]]),'
')
cat(treedist(speciestree,windowtrees[[282]]),'
')
cat(treedist(speciestree,windowtrees[[283]]),'
')
cat(treedist(speciestree,windowtrees[[284]]),'
')
cat(treedist(speciestree,windowtrees[[285]]),'
')
cat(treedist(speciestree,windowtrees[[286]]),'
')
cat(treedist(speciestree,windowtrees[[287]]),'
')
cat(treedist(speciestree,windowtrees[[288]]),'
')
cat(treedist(speciestree,windowtrees[[289]]),'
')
cat(treedist(speciestree,windowtrees[[290]]),'
')
cat(treedist(speciestree,windowtrees[[291]]),'
')
cat(treedist(speciestree,windowtrees[[292]]),'
')
cat(treedist(speciestree,windowtrees[[293]]),'
')
cat(treedist(speciestree,windowtrees[[294]]),'
')
cat(treedist(speciestree,windowtrees[[295]]),'
')
cat(treedist(speciestree,windowtrees[[296]]),'
')
cat(treedist(speciestree,windowtrees[[297]]),'
')
cat(treedist(speciestree,windowtrees[[298]]),'
')
cat(treedist(speciestree,windowtrees[[299]]),'
')
cat(treedist(speciestree,windowtrees[[300]]),'
')
cat(treedist(speciestree,windowtrees[[301]]),'
')
cat(treedist(speciestree,windowtrees[[302]]),'
')
cat(treedist(speciestree,windowtrees[[303]]),'
')
cat(treedist(speciestree,windowtrees[[304]]),'
')
cat(treedist(speciestree,windowtrees[[305]]),'
')
cat(treedist(speciestree,windowtrees[[306]]),'
')
cat(treedist(speciestree,windowtrees[[307]]),'
')
cat(treedist(speciestree,windowtrees[[308]]),'
')
cat(treedist(speciestree,windowtrees[[309]]),'
')
cat(treedist(speciestree,windowtrees[[310]]),'
')
cat(treedist(speciestree,windowtrees[[311]]),'
')
cat(treedist(speciestree,windowtrees[[312]]),'
')
cat(treedist(speciestree,windowtrees[[313]]),'
')
cat(treedist(speciestree,windowtrees[[314]]),'
')
cat(treedist(speciestree,windowtrees[[315]]),'
')
cat(treedist(speciestree,windowtrees[[316]]),'
')
cat(treedist(speciestree,windowtrees[[317]]),'
')
cat(treedist(speciestree,windowtrees[[318]]),'
')
cat(treedist(speciestree,windowtrees[[319]]),'
')
cat(treedist(speciestree,windowtrees[[320]]),'
')
cat(treedist(speciestree,windowtrees[[321]]),'
')
cat(treedist(speciestree,windowtrees[[322]]),'
')
cat(treedist(speciestree,windowtrees[[323]]),'
')
cat(treedist(speciestree,windowtrees[[324]]),'
')
cat(treedist(speciestree,windowtrees[[325]]),'
')
cat(treedist(speciestree,windowtrees[[326]]),'
')
cat(treedist(speciestree,windowtrees[[327]]),'
')
cat(treedist(speciestree,windowtrees[[328]]),'
')
cat(treedist(speciestree,windowtrees[[329]]),'
')
cat(treedist(speciestree,windowtrees[[330]]),'
')
cat(treedist(speciestree,windowtrees[[331]]),'
')
cat(treedist(speciestree,windowtrees[[332]]),'
')
cat(treedist(speciestree,windowtrees[[333]]),'
')
cat(treedist(speciestree,windowtrees[[334]]),'
')
cat(treedist(speciestree,windowtrees[[335]]),'
')
cat(treedist(speciestree,windowtrees[[336]]),'
')
cat(treedist(speciestree,windowtrees[[337]]),'
')
cat(treedist(speciestree,windowtrees[[338]]),'
')
cat(treedist(speciestree,windowtrees[[339]]),'
')
cat(treedist(speciestree,windowtrees[[340]]),'
')
cat(treedist(speciestree,windowtrees[[341]]),'
')
cat(treedist(speciestree,windowtrees[[342]]),'
')
cat(treedist(speciestree,windowtrees[[343]]),'
')
cat(treedist(speciestree,windowtrees[[344]]),'
')
cat(treedist(speciestree,windowtrees[[345]]),'
')
cat(treedist(speciestree,windowtrees[[346]]),'
')
cat(treedist(speciestree,windowtrees[[347]]),'
')
cat(treedist(speciestree,windowtrees[[348]]),'
')
cat(treedist(speciestree,windowtrees[[349]]),'
')
cat(treedist(speciestree,windowtrees[[350]]),'
')
cat(treedist(speciestree,windowtrees[[351]]),'
')
cat(treedist(speciestree,windowtrees[[352]]),'
')
cat(treedist(speciestree,windowtrees[[353]]),'
')
cat(treedist(speciestree,windowtrees[[354]]),'
')
cat(treedist(speciestree,windowtrees[[355]]),'
')
cat(treedist(speciestree,windowtrees[[356]]),'
')
cat(treedist(speciestree,windowtrees[[357]]),'
')
cat(treedist(speciestree,windowtrees[[358]]),'
')
cat(treedist(speciestree,windowtrees[[359]]),'
')
cat(treedist(speciestree,windowtrees[[360]]),'
')
cat(treedist(speciestree,windowtrees[[361]]),'
')
cat(treedist(speciestree,windowtrees[[362]]),'
')
cat(treedist(speciestree,windowtrees[[363]]),'
')
cat(treedist(speciestree,windowtrees[[364]]),'
')
cat(treedist(speciestree,windowtrees[[365]]),'
')
cat(treedist(speciestree,windowtrees[[366]]),'
')
cat(treedist(speciestree,windowtrees[[367]]),'
')
cat(treedist(speciestree,windowtrees[[368]]),'
')
cat(treedist(speciestree,windowtrees[[369]]),'
')
cat(treedist(speciestree,windowtrees[[370]]),'
')
cat(treedist(speciestree,windowtrees[[371]]),'
')
cat(treedist(speciestree,windowtrees[[372]]),'
')
cat(treedist(speciestree,windowtrees[[373]]),'
')
cat(treedist(speciestree,windowtrees[[374]]),'
')
cat(treedist(speciestree,windowtrees[[375]]),'
')
cat(treedist(speciestree,windowtrees[[376]]),'
')
cat(treedist(speciestree,windowtrees[[377]]),'
')
cat(treedist(speciestree,windowtrees[[378]]),'
')
cat(treedist(speciestree,windowtrees[[379]]),'
')
cat(treedist(speciestree,windowtrees[[380]]),'
')
cat(treedist(speciestree,windowtrees[[381]]),'
')
cat(treedist(speciestree,windowtrees[[382]]),'
')
cat(treedist(speciestree,windowtrees[[383]]),'
')
cat(treedist(speciestree,windowtrees[[384]]),'
')
cat(treedist(speciestree,windowtrees[[385]]),'
')
cat(treedist(speciestree,windowtrees[[386]]),'
')
cat(treedist(speciestree,windowtrees[[387]]),'
')
cat(treedist(speciestree,windowtrees[[388]]),'
')
cat(treedist(speciestree,windowtrees[[389]]),'
')
cat(treedist(speciestree,windowtrees[[390]]),'
')
cat(treedist(speciestree,windowtrees[[391]]),'
')
cat(treedist(speciestree,windowtrees[[392]]),'
')
sink()
